// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TacoKaiju.Models;

namespace TacoKaiju.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TacoKaiju.Models.Taco", b =>
                {
                    b.Property<int>("TacoId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Calories");

                    b.Property<string>("Fillings");

                    b.Property<string>("Protein");

                    b.Property<string>("ShellType");

                    b.HasKey("TacoId");

                    b.ToTable("Tacos");
                });
#pragma warning restore 612, 618
        }
    }
}
